### ISSUE TITLE
Redesign app 

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid-web#27]
Opsdroid Web doesn't look bad, but it might be a good idea to give it a fresh new look. Here are the two proposals for the redesign, I'm wondering if perhaps we should have these two colours and let users select whichever they prefer.  I'm also wondering which style for the chat bubbles to choose from.

<img width="1086" alt="Screenshot 2022-06-14 at 23 20 50" src="https://user-images.githubusercontent.com/3131401/173699197-fb45debc-3cd1-41bb-89d3-51ced4fc4787.png">

Here's the [figma link](https://www.figma.com/file/a6oxeSHiufB2ourMVkp6CY/Opsdroid-web-v2) so you can see the design better. I will also be updating this with the settings tab

**Comment by Cadair** [comment]
I wonder if you could turn the dark blue colours into a dark theme and the light green into a light theme and have them both?!

**Comment by Cadair** [comment]
The light colour text entry box contrast is a little low, you might be better off going for black. I think the black on green contrast for the chat bubbles is easier to read though.

**Comment by FabioRosado** [comment]
Thank you for the feedback Cadair! That makes a lot of sense I'll address your comments on the contrast.
I've also had a bit more thought and I think it would be nice to offer the two colours as accent colours, plus a dark theme for both. Hopefully this won't be too tricky to implement

**Comment by FabioRosado** [comment]
Two more updates, here's the settings tab. I'm considering changing the icons on the navbar to include just settings and maybe that connect icon with "connected/disconnected" text. Hitting that will toggle the connection component.

<img width="509" alt="Screenshot 2022-06-15 at 20 31 13" src="https://user-images.githubusercontent.com/3131401/173909495-aa44702a-7e6c-4dcf-b985-87789bc36e9d.png">

This is the two themes, dark and light for the blue accent colour
<img width="1224" alt="Screenshot 2022-06-15 at 20 33 26" src="https://user-images.githubusercontent.com/3131401/173909500-ff56b9cd-20b2-4de4-9183-45da7704dbb7.png">
