### ISSUE TITLE
Reduce payload size

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid-web#5]
After webpacking the application we get a warning saying it is quite big. We should look at reducing this.

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  main.js (1.19 MiB)
```

**Comment by FabioRosado** [comment]
We can close this issue now, the whole APP is currently sitting at 1.1MB.
After building all the JS files are 871 KB and `main` is 204 KB
